# Generated by Django 3.1.4 on 2021-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('igrica', models.CharField(max_length=50)),
                ('rezultat', models.IntegerField()),
            ],
        ),
    ]
