# Generated by Django 3.1.4 on 2021-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igrica',
            options={'verbose_name_plural': 'igrice'},
        ),
        migrations.AlterField(
            model_name='igrica',
            name='igrica',
            field=models.CharField(choices=[('Memorija', 'Memorija'), ('Reakcija', 'Reakcija'), ('Brzina', 'Brzina')], max_length=50),
        ),
    ]
