# Generated by Django 3.1.4 on 2021-02-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrice', '0002_auto_20210102_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgricaMemorije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('pokusaji', models.IntegerField()),
                ('vreme', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'igrice',
            },
        ),
        migrations.DeleteModel(
            name='Igrica',
        ),
    ]
