# Generated by Django 3.1.4 on 2021-02-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igrice', '0003_auto_20210201_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igricamemorije',
            options={'verbose_name_plural': 'Igrice memorije'},
        ),
    ]
