# Generated by Django 3.1.4 on 2021-02-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrice', '0004_auto_20210201_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upitnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_i_prezime', models.CharField(max_length=40)),
                ('email_adresa', models.EmailField(max_length=50)),
                ('Igra_memorije', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('Igra_brzine', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('Igra_reakcije', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('iskustvo', models.CharField(choices=[('Odlično', 'Odlično'), ('Dobro', 'Dobro'), ('Loše', 'Loše')], max_length=20)),
                ('omiljena_igra', models.CharField(choices=[('Igra Memorije', 'Igra Memorije'), ('Igre Reakcije', 'Igre Reakcije'), ('Igra Brzine', 'Igra Brzine')], max_length=20)),
                ('Vaš_Utisak', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Upitnici',
            },
        ),
    ]
