# Generated by Django 3.1.4 on 2021-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrice', '0005_upitnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgricaBrzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('klikovi', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Igrice brzine',
            },
        ),
        migrations.CreateModel(
            name='IgricaReakcije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('vreme', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Igrice reakcije',
            },
        ),
    ]
